---
contao:
  localconfig:
    uploadTypes: 'jpg,jpeg,png,gif,svg,webp,pdf,dxf,dwg,step,stp,stl,iges,igs'
  image:
    sizes:
      _defaults:
        formats:
          jpg: [webp, jpg]
          png: [webp, png]
        densities: 1.5x
        lazy_loading: true
        resize_mode: crop
      herosection:
        lazy_loading: false
        width: 580
        height: 348
        items:
          - media: '(min-width: 1280px)'
            width: 1920
          - media: '(min-width: 1024px)'
            width: 1280
          - media: '(min-width: 768px)'
            width: 910
            height: 546
          - media: '(min-width: 640px)'
            width: 700
            height: 420
      herosectionbg:
        lazy_loading: false
        width: 480
        height: 480
        items:
          - media: '(min-width: 1024px)'
            width: 1800
            height: 866
          - media: '(min-width: 768px)'
            width: 720
            height: 576
          - media: '(min-width: 640px)'
            width: 630
            height: 480
          - media: '(min-width: 480px)'
            width: 450
            height: 384
      textmedia:
        width: 560
        height: 420
        items:
          - media: '(min-width: 1024px)'
            width: 672
            height: 560
          - media: '(min-width: 768px)'
            width: 912
            height: 684
          - media: '(min-width: 640px)'
            width: 680
            height: 510
      textimage:
        width: 560
        height: 560
        items:
          - media: '(min-width: 1024px)'
            width: 672
            height: 672
          - media: '(min-width: 768px)'
            width: 912
            height: 912
          - media: '(min-width: 640px)'
            width: 680
            height: 680
      imageshowcase:
        resize_mode: proportional
        width: 450
        items:
          - media: '(min-width: 1024px)'
            width: 1280
          - media: '(min-width: 768px)'
            width: 912
          - media: '(min-width: 640px)'
            width: 680
          - media: '(min-width: 480px)'
            width: 560
      gridsection:
        width: 420
        height: 280
        items:
          - media: '(min-width: 768px)'
            width: 444
            height: 296
          - media: '(min-width: 640px)'
            width: 680
            height: 560
          - media: '(min-width: 480px)'
            width: 564
            height: 376
